name: Deploy on Commit to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v2

      # Set up Git configuration (now after the checkout)
      - name: Set up Git configuration
        run: |
          git config user.email "nk.angelovv@gmail.com"
          git config user.name "Nikolay Angelov"

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run the deploy command
      - name: Run deploy script
        run: CI=false npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
